---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
  - repo: https://github.com/mrtazz/checkmake
    rev: '0.2.2'
    hooks:
      - id: checkmake
  - repo: https://github.com/PyCQA/docformatter
    rev: 'v1.7.5'
    hooks:
      - id: docformatter
  - repo: https://github.com/hadolint/hadolint
    rev: 'v2.12.1-beta'
    hooks:
      - id: hadolint
        args: [--ignore, DL3006, --ignore, DL3013]
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
  - repo: https://github.com/executablebooks/mdformat
    rev: '0.7.17'
    hooks:
      - id: mdformat
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
      - id: mypy
        additional_dependencies: [alembic]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.287'
    hooks:
      - id: ruff
  - repo: https://github.com/adrienverge/yamllint
    rev: 'v1.32.0'
    hooks:
      - id: yamllint
