---
version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: artms
      POSTGRES_PASSWORD: artms
    ports:
      - 5432:5432
    volumes:
      - artms-data:/var/lib/postgresql/data

volumes:
  artms-data:
